server:
  port: 8022
spring:
  application:
    name: LangChain4JRun
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 5s



langchain4j:
  open-ai:
    chat-model:
      api-key: sk-1441e7cd83c0411290f22624175a1d78
      model-name: qwen-max-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: sk-1441e7cd83c0411290f22624175a1d78
      model-name: qwen-max-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true




